# Generated by Django 5.2.13 on 2026-06-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='username1',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
