# Generated by Django 5.2.13 on 2026-06-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSite', '0002_user_info_username1'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
