# Generated by Django 5.2.13 on 2026-06-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSite', '0003_device_assigned_date_device_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='assigned_date',
        ),
        migrations.AddField(
            model_name='device',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
